### ISSUE TITLE
Stop function (and aplay)

### ISSUE THREAD

**Issue by verth** [shime/play-sound#13]
Noticed you took over `play.js` (after noticing it was a bit nonactive), nice job!  :+1: 

An open issue there was a request for stop functionality, thought of mentioning it here too as it still seems pretty relevant to this package.

Could probably be done with `spawn` instead of `exec`, hold reference and kill child, may possible also (partially) resolve https://github.com/shime/play-sound/issues/12.

(Also, was thinking, perhaps `aplay` could be added to the default players? It is pretty common on Linux systems)

**Comment by shime** [comment]
Thanks for reporting. Just published `1.1.1` with `aplay` added to details, and @justinjmoses added support for holding a reference to `child_process` so you can kill it later. Check the readme for more info.
