### ISSUE TITLE
Ability to adjust output volume.

### ISSUE THREAD

**Issue by mralexgray** [shime/play-sound#14]
You be nice if we were able to set the volume on some sort of scale for each sound played.

**Comment by shime** [comment]
Just bumped the version to `1.1.0`, @justinjmoses added support for that. Check the readme for more details.

**Comment by traumst** [comment]
I'm using your library in nodejs app on Ubuntu and the example does not change the **volume** for me. Can you please give another example of adjusting the it? 
Not finding an answer just by reviewing the code. Nothing on the mplayer site either.
