### ISSUE TITLE
player does not auto-detect

### ISSUE THREAD

**Issue by matt-cook** [shime/play-sound#2]
Worked correctly only when player was specified in options. OSX 10.10.1, Node.js 0.10.22

**Comment by shime** [comment]
which players do you have installed?

**Comment by matt-cook** [comment]
afplay only.

**Comment by vergissberlin** [comment]
Hi, I have the same problem. I found out, it is more a bug of _[find-exec](https://github.com/shime/find-exec)_.
It always returns _null_.

On myCLI (OS X 10.9.5) I do
```bash
  which afplay
  /usr/bin/afplay
```

So I tried to get the same output with _exec-sync_ 
```javascript
var exec = require('exec-sync');

exec(['which afplay'], function(err, out, code) {
	if (err instanceof Error)
		throw err;
	process.stderr.write(err);
	process.stdout.write(out);
	process.exit(code);
});
````
and i got _null_.
Unfortunately, I found no solution to the problem. But maybe this helps.

André

**Comment by shime** [comment]
Thanks for bumping this. I guess it's an issue with `exec-sync` and OSX. I've just bumped the version on NPM, so please try updating the package version with `npm install play-sound`. 

If that doesn't help, try running this
```js
var exec = require('execSync').exec
console.log(exec('afplay').code) // should print 0
```

**Comment by vergissberlin** [comment]
**Thank you for the quick reply!*
Unfortunately, the update did not help.

With your snippet and an installed execSync package I get a 1 on the console.
In _execSync_ instruction I found, that sometimes is the need to install _node-gyp_ globally
```
npm install node-gyp -g
```
But after I have installed, it also returns 1;
So I asked my self, what if _afplay_ always returns 1, if you don't pass an argument?
And I tried this:
```javascript
var exec = require('execSync').exec;
console.log(exec('afplay assets/test.mp3').code);
```
Et voilá. C'est tout. It returns 0. It also return 1, if your argument is not a valid path to a sound file.

Maybe you can use commands like follows, to check the player exists
```bash
$ command -v foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }
$ type foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }
$ hash foo 2>/dev/null || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }
```

André

**Comment by shime** [comment]
Thanks for the suggestion André! Bumped the version on NPM again, it should be fixed now.

**Comment by vergissberlin** [comment]
**Hi shime,**

sorry, _find-exec_ still returns NULL on OS X with afplay.

```javascript
var command = require('find-exec')(["mplayer", "afplay", "cvlc"])
console.log(command) // >> null
```

regards, André

**Comment by shime** [comment]
LOL, I need to borrow a MacBook for this one.

**Comment by vergissberlin** [comment]
Maybe https://saucelabs.com/ could help to get it stable. 
For Open Source projects it is for free and you can run your test code also on OS X.

https://docs.saucelabs.com/tutorials/node-js/
https://docs.saucelabs.com/tutorials/js-unit-testing/

André

**Comment by shime** [comment]
Figured out it was a silly error from my side causing this, the regex `/win/` was matching both `win32` and `darwin`, so I had to alter it a bit to match windows only.
