### ISSUE TITLE
Opts is not defined

### ISSUE THREAD

**Issue by 16alexanders** [shime/play-sound#20]
When I try to use the module it throws an error....

`ReferenceError: opts is not defined`

Not sure whats going on here.... when I try to remove `(opts = {})` then it says there is no method called `.play()` can't seem to get around this error

**Comment by shime** [comment]
Stop defining opts in arguments. 

```js
var player = require('play-sound')()

// $ mplayer foo.mp3 
player.play('foo.mp3', function(err){
  if (err) throw err
})
```

**Comment by 16alexanders** [comment]
Yeah I had use-strict enabled and it didn't like the undeclared variable
