### ISSUE TITLE
not working in windows 10 x64

### ISSUE THREAD

**Issue by ferdiozer** [shime/play-sound#39]
`const player = require('play-sound')();`

`      player.play('alert.mp3', (err) => { 
        if (err) console.log(`Could not play sound: ${err}`);
    });`
Error: Couldn't find a suitable audio player
Error: INFO: Could not find files for the given pattern(s).

Thank you

**Comment by kot-shrodingera** [comment]
You need to install compatable console player (mplayer for example) and make it available in the shell (add mplayer folder to %PATH%)

**Comment by ferdiozer** [comment]
![image](https://user-images.githubusercontent.com/18518803/68369107-95c2ca00-014a-11ea-9317-f91c423751f0.png)

![image](https://user-images.githubusercontent.com/18518803/68369159-b25f0200-014a-11ea-93e0-9b4293e5b999.png)


I can not.
i guess i couldnt

**Comment by kot-shrodingera** [comment]
If you go to your project directory in cmd and type `mplayer alert.mp3` is it playing?

**Comment by ferdiozer** [comment]
![image](https://user-images.githubusercontent.com/18518803/68391274-485d5180-0178-11ea-8622-ff00b79f239d.png)

Yeah, it's ringing. It does not work anymore. It worked when I turned on the computer again. Thank you

**Comment by ferdiozer** [comment]
![image](https://user-images.githubusercontent.com/18518803/68391392-91ada100-0178-11ea-9cd4-f8eebb4e2d36.png)
Is that the right thing?
system variables?
or user variables?

**Comment by kirax999** [comment]
I found a solution if other people have the same error

download mplayer in https://mplayerhq.hu/design7/dload.html scroll for middle page and download "windows Binaries" after download please uncompress 

and copy mplayer.exe in main directory project

play-sound not use path in windows just search in main directory project

**Comment by scyto** [comment]
ok possible fix

download mplayer from here and either add to your path variables or extract contents into the root of you project http://mplayerwin.sourceforge.net/downloads.html

this was from https://github.com/shime/play-sound/issues/39

no idea if it works, no idea how to force a testm i have both mplayer and cmdmpe in root of my project now.

**Comment by unional** [comment]
The issue is `find-exec`. 1.0.2 fixed it, but right now `play-sound` pinned to 1.0.1

**Comment by shime** [comment]
I've just published a new version that should fix this issue. Thanks for reminding me, @unional.

**Comment by unional** [comment]
Thank you! :)
