### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by dpriskorn** [shime/play-sound#44]
In case yes I suggest trying to find someone to take over. You got 5 pull requests unanswered.

**Comment by lutzer** [comment]
yes, it would be great if the pull requests could be merged in.

**Comment by g5fighter** [comment]
Please, make this repo go active again

**Comment by shime** [comment]
Sorry for not responding, I've been busy lately. I'll go through the PRs, thanks for reminding me.
