### ISSUE TITLE
RaspberryPi support

### ISSUE THREAD

**Issue by omarojo** [shime/play-sound#5]
I get errors when installing in RaspberryPi, something about the execSync.

**Comment by shime** [comment]
could you paste the stack trace?

**Comment by roosnic1** [comment]
Hi @shime I don't know if @omarojo had the same problem but my installation on the raspberry pi failed as well during execSync. I have a normal Raspberry Pi 2 with the newest raspbian OS running on it. I installed node and npm and had no problems with other node modules. But when I tried to install play-sound I get the following error.

```sh
pi@raspberrypi ~/iBeacon-Scanner- $ npm install play-sound
\
> execSync@1.0.2 install /home/pi/iBeacon-Scanner-/node_modules/play-sound/node_modules/find-exec/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
play-sound@0.0.5 node_modules/play-sound
└── find-exec@0.0.7 (execSync@1.0.2)
pi@raspberrypi ~/iBeacon-Scanner- $
```

**Comment by shime** [comment]
Hey guys, thanks for reporting! I've now removed problematic `execSync` as a dependency and updated the version. Hopefully this fixes things for you. If not, please reopen this issue.
